# Generated by Django 5.1.1 on 2024-09-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapinghistory',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
