# Generated by Django 5.1.1 on 2024-10-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_alter_scrapinghistory_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapinghistory',
            name='keyword',
            field=models.TextField(blank=True, null=True),
        ),
    ]
