# Generated by Django 3.2.13 on 2022-05-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userimage',
            table='user_images',
        ),
    ]
