# Generated by Django 3.2.4 on 2021-07-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_alter_userimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
