# Generated by Django 3.2.4 on 2021-07-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_auto_20210713_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
