FROM node:latest

# install package.
# RUN set -x && \
#     apt-get install -y sudo \
#     wget \
#     git \
#     init \
#     curl \
#     openssh-server \
#     openssh-client

# Change host user.
# ARG UID=1000
# ARG GID=1000
# ARG USER=yohei
# ARG GROUP=yohei
# ARG PASS=yohei
# RUN groupadd -g $GID $GROUP && \
#     useradd -m -s /bin/bash -u $UID -g $GID -G sudo $USER && \
#     echo $USER:$PASS | chpasswd && \
#     echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
# USER ${USER}:${GROUP}
# WORKDIR /home/${USER}
